spring.application.name=hub
server.port=8082

# MySQL Connection Settings
spring.datasource.url=jdbc:mysql://localhost:3306/hub_db?serverTimezone=UTC
spring.datasource.username=rey
spring.datasource.password=mchunky8
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Settings
# Use 'update' for development; switch to 'validate' or 'none' in production
# 'create-drop' to rebuild db tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# Reactive MySQL Connection Settings (R2DBC)
# Advanced R2DBC URL with encoded parameters
# Example includes: serverZoneId=UTC (UTC), useServerPrepareStatement=true, and zeroDate=use_null
# spring.r2dbc.url=r2dbc:pool:mysql://localhost:3306/hub_db
# spring.r2dbc.username=rey
# spring.r2dbc.password=mchunky8
